name = "Not Entirely Unlike Cupper"
license = "MIT"
licenselink = "https://github.com/rp-magrathea/not-entirely-unlike-cupper/blob/master/LICENSE"
description = "Documentation theme for Magrathea's various \"lego libraries.\" Based on Cupper (https://github.com/ThePacielloGroup/cupper)"
homepage = "https://github.com/rp-magrathea/not-enitrely-unlike-cupper"
tags = ["documentation", "pattern library"]
features = ["light/dark themes"]
min_version = "0.80.0"

SectionPagesMenu = "main"

[author]
  name = "Daine"
  homepage = "https://daine.dev"

# porting an existing theme
[original]
  name = "Heydon Pickering"
  homepage = "https://heydonworks.com"
  repo = "https://github.com/ThePacielloGroup/cupper"

[taxonomies]
  tag = "tags"
  wcag = "wcag"
  principle = "principles"
