title: Not Entirely Unlike Cupper

baseURL: "https://magrathea.guide/not-entirely-unlike-cupper"
canonifyURLs: true
languageCode: en-US
publishDir: static/lego-library
theme: not-entirely-unlike-cupper

params:
    codePenUser: littlelark
    description: Documentation theme for Magrathea's various "lego libraries." Based on [Cupper](https://github.com/ThePacielloGroup/cupper).

markup:
    highlight:
        codeFences: false
        style: bw
