---
name: Check Style

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

jobs:
    lint:
        name: Super-Linter
        runs-on: ubuntu-latest

        steps:
            - name: Checkout Code
              uses: actions/checkout@v2

            - name: NPM Install
              uses: bahmutov/npm-install@v1

            - name: Run super-linter
              uses: github/super-linter@v3
              env:
                  CSS_FILE_NAME: .stylelintrc.yml
                  DEFAULT_BRANCH: main
                  FILTER_REGEX_EXCLUDE: .*node_modules.*|.*dist\/assets\/stylesheet.css
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  LINTER_RULES_PATH: tools
                  VALIDATE_JAVASCRIPT_STANDARD: false

    prettier:
        name: Prettier
        runs-on: ubuntu-latest

        steps:
            - name: Checkout Code
              uses: actions/checkout@v2

            - name: NPM Install
              uses: bahmutov/npm-install@v1

            - name: Run Prettier check
              run: npm run-script prettier:check
